behaviors:
  Curriculum_1:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        strength: 0.1
        gamma: 0.8
      gail:
        strength: 0.5
        gamma: 0.8
        demo_path: Assets/FlapAI/AI/Scripts/Demos/DeeStage1.demo
    behavioral_cloning:
      strength: 1.0
      gamma: 0.8
      demo_path: Assets/FlapAI/AI/Scripts/Demos/DeeStage1.demo
    max_steps: 5000000
    time_horizon: 2048
    summary_freq: 20000
